# External Gems
gems: 						[jekyll-paginate]

# Site Settings
title: 						"hietech fe team"
url:						"http://hietech.github.io"
email: 						"yipeng.info@gmail.com"
description: 			"为能源与设施经济安全可控。"
baseurl: 					""
logourl: 					"/files/common/avatar.jpg"
fa-logo: 					"fa-camera-retro"
paginate: 					10
paginate_path: "weblog/:num"

# Author Settings
author_name: 				"hietech fe team"
author_url: 				"http://hietech.github.io"
author_bio: 				"专注设施能源领域。"
author_email: 			"yipeng.info@gmail.com"
author_image: 				"/files/common/avatar.jpg"


# Social Settings

github_url:  			"https://github.com/hietech"
weibo_url: 					"http://weibo.com/hietech2006"
youtube_url:  				""
dribbble_url:  				""
googleplus_url: 			""
instagram_url:  			""
pinterest_url:  			""
linkedin_url:  				""


# Theme Settings
theme_disqus_shortname: 	"yuguo"
theme_google_comments: 		false
theme_analytics_id: 		"UA-741276-12"
theme_reading_time: 		true
theme_autoload_comments: 	true
theme_always_show_nav: 		true


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					weblog/:title/

